// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'api',
    appId: '1:355328288359:web:63bbc6bd93b1ce554c56c2',
    messagingSenderId: '355328288359',
    projectId: 'cashxchange-a07f7',
    authDomain: 'cashxchange-a07f7.firebaseapp.com',
    storageBucket: 'cashxchange-a07f7.appspot.com',
    measurementId: 'G-8LZ0FMQK1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'api',
    appId: '1:355328288359:android:56c55a458ef9fd644c56c2',
    messagingSenderId: '355328288359',
    projectId: 'cashxchange-a07f7',
    storageBucket: 'cashxchange-a07f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'api',
    appId: '1:355328288359:ios:2583d3a14799327f4c56c2',
    messagingSenderId: '355328288359',
    projectId: 'cashxchange-a07f7',
    storageBucket: 'cashxchange-a07f7.appspot.com',
    iosClientId:
        '355328288359-v2e88vb7v8e20ceka3dabqtvgi756kgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashxchange',
  );
}
